/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regandlogin;
import javax.swing.JOptionPane;
/**
 *
 * @author Jishan Aich
 */
public class LoginPage extends javax.swing.JFrame {
    
    Database db;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        db=new Database();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reg_tf_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reg_tf_roll = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        reg_tf_pno = new javax.swing.JTextField();
        reg_b_sub = new javax.swing.JButton();
        reg_b_cle = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_ser = new javax.swing.JTextField();
        ser_b = new javax.swing.JButton();
        ser_lab1 = new javax.swing.JLabel();
        ser_lab2 = new javax.swing.JLabel();
        ser_lab3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APP BANAYA HU YAAR");

        jLabel1.setText("Register:-");

        jLabel2.setText("Name:");

        reg_tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_tf_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("Roll:");

        jLabel4.setText("Phone #:");

        reg_tf_pno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_tf_pnoActionPerformed(evt);
            }
        });

        reg_b_sub.setText("Submit");
        reg_b_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_b_subActionPerformed(evt);
            }
        });

        reg_b_cle.setText("Clear");
        reg_b_cle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_b_cleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reg_tf_pno))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reg_tf_roll))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reg_tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(reg_b_sub)
                        .addGap(34, 34, 34)
                        .addComponent(reg_b_cle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(reg_tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reg_tf_roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reg_tf_pno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_b_sub)
                    .addComponent(reg_b_cle))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel5.setText("Search:-");

        ser_b.setText("Search");
        ser_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ser_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ser_lab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(475, 475, 475))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ser_lab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(475, 475, 475))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ser_lab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(289, 289, 289))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ser_b)))
                        .addGap(186, 186, 186))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ser_b))
                .addGap(18, 18, 18)
                .addComponent(ser_lab1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ser_lab2, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ser_lab3, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addGap(160, 160, 160))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg_tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_tf_nameActionPerformed

    private void reg_tf_pnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_tf_pnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_tf_pnoActionPerformed

    private void reg_b_cleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_b_cleActionPerformed
                  reg_tf_name.setText("");
                  reg_tf_roll.setText("");
                  reg_tf_pno.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_reg_b_cleActionPerformed

    private void reg_b_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_b_subActionPerformed
        String reg_name=reg_tf_name.getText();
        String reg_roll=reg_tf_roll.getText();
        String reg_pno=reg_tf_pno.getText();
        String query="INSERT INTO STUDENT VALUES('"+reg_name+"','"+reg_roll+"','"+reg_pno+"')";
        Boolean i=null;
        try
        {
            i=db.stmt.execute(query);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        if(!i)
        {
            JOptionPane.showMessageDialog(this, "Successful");
        }
        else
        {
            System.out.println("Unsuccessful");
        }// TODO add your handling code here:
    }//GEN-LAST:event_reg_b_subActionPerformed

    private void ser_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ser_bActionPerformed
        String db_roll=null;
        String db_name=null;
        String db_pno=null;
        String reg_roll=tf_ser.getText();
        String query="SELECT * FROM STUDENT WHERE ROLL='"+reg_roll+"'";
        System.out.println(query);
        try
        {
            db.rs=db.stmt.executeQuery(query);
            db.rs.next();
            db_name=db.rs.getString(1);
            db_roll=db.rs.getString(2);
            db_pno=db.rs.getString(3);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        if(reg_roll.equals(db_roll))
        {
           ser_lab1.setText("The name is "+db_name);
           ser_lab2.setText("The roll is "+db_roll);
           ser_lab3.setText("The phone# is "+db_pno);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"UNSUCESSFUL SEARCH");
        }// TODO add your handling code here:
    }//GEN-LAST:event_ser_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reg_b_cle;
    private javax.swing.JButton reg_b_sub;
    private javax.swing.JTextField reg_tf_name;
    private javax.swing.JTextField reg_tf_pno;
    private javax.swing.JTextField reg_tf_roll;
    private javax.swing.JButton ser_b;
    private javax.swing.JLabel ser_lab1;
    private javax.swing.JLabel ser_lab2;
    private javax.swing.JLabel ser_lab3;
    private javax.swing.JTextField tf_ser;
    // End of variables declaration//GEN-END:variables
}
